- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux,shell, ansible, terraform
    tagsList:
    name: ansible
    project: roboshop
    component: catalogue  
  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi Kiran {{ GREETING | default('Good Morning') }}"

  - name: covert string  to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: covert map to list
    ansible.builtin.debug:
      msg: "{{ tagsList | dict2items }}"    
